### ISSUE TITLE
Any way to get a newer build of gamescope?

### ISSUE THREAD

**Issue by kassindornelles** [flathub/com.valvesoftware.Steam.Utility.gamescope#8]
The actual build causes mouse issues in several games including resident evil village, and grand theft auto v
you can't click in anything in the screen or use your mouse at all in the actual shipping build in flatpak.

**Comment by kassindornelles** [comment]
consider adding git since gamescope is a work in progress anyway.

**Comment by CyborgDragonFire** [comment]
Issues with the build have been fixed, and a pull request updating to the latest gamescope build 3.11.5 is currently pending.
You can follow things in the pull request #11

**Comment by kassindornelles** [comment]
i still can't launch any game with flatpaked gamescope, i use `gamescope -e -f`normally in non-flatpak steam and it works, the version you are packaging is probably too old

**Comment by kassindornelles** [comment]
this tag: [3.11.28-beta4](https://github.com/Plagman/gamescope/releases/tag/3.11.28-beta4) should work

**Comment by TheGreatestJannet** [comment]
Looks like it is out of date again. Any plans to update it?

**Comment by SuNNjek** [comment]
So, is this flatpak effectively abandoned? There have been multiple releases since the flatpak has been updated last

**Comment by Bananaman** [comment]
It's a shame that the official https://github.com/Plagman/gamescope didn't want to release a flatpak. All flatpak games rely on having a gamescope flatpak. And flatpak is becoming the main app distribution method.

**Comment by TheGreatestJannet** [comment]
One of the reasons might be that it doesn’t actually work correctly in flatpak steam games using Proton 5.13+ which is one of its biggest use cases.

**Comment by Bananaman** [comment]
We can close this ticket. Thanks to @Pixelnarium we now have automatic updates to the latest official releases of gamescope. #15
